Milestone2
RICKCOYL/Book-store pull request #2
Opened 2021-04-25 05:37 UTC by RICKCOYL

2021-04-25 10:31 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @RICKCOYL and @Morrism1! 👋 
 You have also done a wonderful job with this milestone so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
**BooksList Component**

- [ ]  The booklist component should be connected to the redux store using the [connect() function](https://react-redux.js.org/api/connect) or [Redux hooks](https://react-redux.js.org/api/hooks) so that it can fetch the books from the state. 
Requirements from pathwright 👇🏾 
<img width="902" alt="Screen Shot 2021-04-25 at 12 25 19 PM" src="https://user-images.githubusercontent.com/48804258/115989998-4df36500-a5c1-11eb-98e0-6095336a1a78.png">

- [ ] Please make sure you are passing the `book` object as a prop. You should be rendering the `Book` component in the body of the table and passing the `book` object as a prop to each `Book` component.

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-04-25 10:31 UTC, BrittanyBlake commented on src/containers/BooksList.js
> +        </tbody>
- [ ] Your BookList component should display a list of the books using the `Book` component
Requirement from pathwright 👇🏾 
<img width="482" alt="Screen Shot 2021-04-25 at 12 27 24 PM" src="https://user-images.githubusercontent.com/48804258/115990065-99a60e80-a5c1-11eb-876f-842b770f47af.png">

2021-04-25 10:31 UTC, BrittanyBlake commented on src/containers/BooksList.js
> +export default function BooksList() {
- [ ] The `book object` should be passed as a prop and passed to each `Book` component

2021-04-26 08:44 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**## Hi @lap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-04-26 08:51 UTC, merged